# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
 - stage: Build
   jobs:
   - job: FirstJob
     steps:
     - bash: echo Build FirstJob
     - bash: echo Build $(PipelineLevelVariable)
     - bash: echo $(Build.BuildNumber)
     - bash: echo $(Build.BuildId)
     - bash: echo $(System.DefaultWorkingDirectory)
     - bash: ls -R $(System.DefaultWorkingDirectory)
     - bash: echo $(Build.ArtifactStagingDirectory)
   - job: SecondJob 
     steps:
     - bash: echo Second Job

 - stage: DevDeploy
   variables:
    environment: DevDeploy
   jobs:
   - job: FirstDevDeployJob
     steps:
     - bash: echo DevDeployFirst_$(environment)
 - stage: ProdDeploy
   variables:
      global_variable: value   

   jobs:
    - job: job1
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        job_variable1: value1    # this is only available in job1
      steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable1)
      - bash: echo $JOB_VARIABLE1 # variables are available in the script environment too

    - job: job2
      pool:
        vmImage: 'ubuntu-latest'
      variables:
        job_variable2: value2    # this is only available in job2
      steps:
      - bash: echo $(global_variable)
      - bash: echo $(job_variable2)
      - bash: echo $GLOBAL_VARIABLE



