# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest
stages:
 - stage: Build
   jobs:
   - job: FirstJob
     steps:
     - bash: echo Build FirstJob
     - bash: echo Build $(PipelineLevelVariable)
   - job: SecondJob 
     steps:
     - bash: echo Second Job

 - stage: DevDeploy
   variables:
    environment: DevDeploy
   jobs:
   - job: FirstDevDeployJob
     steps:
     - bash: echo DevDeployFirst_$(environment)
 - stage: ProdDeploy
   jobs:
   - job: ProdDeploy
     steps:
     - bash: echo ProdDeploy



