trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: 'latest'
  roleNameCluster: 'my-cluster-eks-cluster-role'
  roleNameNode: 'my-cluster-eks-node-group-role'


steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

# init - backend

- task: TerraformTaskV2@2
  inputs:
    provider: 'aws'
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/microservices/configuration/iaac/aws/kubernetes'
    backendServiceAWS: 'aws-for-terraform'
    backendAWSBucketName: 'terraform-backend-state-yvenstr-123'
    backendAWSKey: 'kubernetes-dev.tfstate'


- script: |
    echo "Importing existing AWS IAM Roles into Terraform State"
    terraform import aws_iam_role.eks_cluster $(roleNameCluster)
    terraform import aws_iam_role.eks_node $(roleNameNode)
  condition: and(succeeded(), eq(variables['ImportRoles'], 'true'))
  displayName: 'Terraform Import IAM Roles'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/microservices/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-for-terraform'
  

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'destroy'
    workingDirectory: '$(System.DefaultWorkingDirectory)/microservices/configuration/iaac/aws/kubernetes'
    environmentServiceNameAWS: 'aws-for-terraform'
