
trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformVersion: 'latest'

  workingDirectory: '$(System.DefaultWorkingDirectory)/test-config-aws'


stages:
 - stage: TerraformH
   jobs:
   - job: init
     steps:
     - script: echo Starting a new proyect with Terraform!
       displayName: 'Starting a new proyect with Terraform'
 - stage: TerraformInit
   jobs:
   - job: TerraformI
     steps:
     - task: TerraformTaskV2@2
       inputs:
        provider: 'aws'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)/test-config-aws'
        backendServiceAWS: 'aws-for-terraform'
        backendAWSBucketName: 'terraform-backend-state-yvenstr-123'
        backendAWSKey: 'kubernetes-dev.tfstate' 

