trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo "Starting the pipeline..."
  displayName: 'Print start message'

- script: echo "Hello World"
  displayName: 'Print Hello World'

- script: echo "Running a sample script..."
  displayName: 'Run sample script'
  bash: |
   echo "This is a bash script"
   echo "It is running on the build server"
   echo "The build server hostname is $HOSTNAME"
   echo "The current working directory is $PWD"
   echo "The current user is $USER"
   echo "The current operating system is $OSTYPE"
   echo "The current shell is $SHELL"
   echo "The current path is $PATH"
   echo "The current date is $(date)"

- script: echo "Compiling code..."
  displayName: 'Compile code'
   # - script: |
   # dotnet build MyProject.sln --configuration Release  --no-restore   
  #displayName: 'Build .NET project'

- script: echo "Running tests..."
  displayName: 'Run tests'
#- script: |
   #dotnet test MyProject.sln
  #   displayName: 'Test .NET project'

- script: echo "Deploying application..."
  displayName: 'Deploy application'
 
  # - script: |
  #     az webapp up --name my-app-service --resource-group my-resource-group
  #   displayName: 'Deploy to Azure App Service'

- script: echo "Pipeline completed successfully."
  displayName: 'Print completion message'